name: Deploy Website

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.json'       # <--- Игнорировать любые обновления JSON-файлов

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # <--- Защита от зависания (максимум 5 минут)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Если вы используете GitHub Pages, этот шаг обновит ваш сайт
      - name: Deploy to GitHub Pages
        uses: Actions-R-Us/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Укажите папку с html, если она отличается от корневой
