name: Deploy Pages Concurrency Limit

on:
  push:
    branches:
      - main # Если ваша главная ветка называется master, напишите master

# ЭТОТ БЛОК АВТОМАТИЧЕСКИ ПРЕКРАЩАЕТ СТАРЫЙ ДЕПЛОЙ ПРИ НОВОМ ПУШЕ
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Нам не нужно описывать шаги сборки, так как GitHub делает это сам.
  # Этот пустой job служит триггером-контроллером для управления очередью.
  control_queue:
    runs-on: ubuntu-latest
    steps:
      - name: Optimizing queue
        run: echo "Managing deployment queue..."
